"""
Django settings for divdprint project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Secrets / environment -------------------------------------------------- #
# Secrets live outside version control. A plain KEY=VALUE `.env` at the project
# root is loaded here (dependency-free) so both gunicorn and the manage.py-based
# services pick it up. Real process env (e.g. systemd Environment=) wins over
# the file. See .env.example for the required keys.
def _load_dotenv(path):
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def _require_env(key):
    value = os.environ.get(key)
    if not value:
        raise ImproperlyConfigured(
            f'Missing required environment variable {key!r}. '
            f'Set it in {BASE_DIR / ".env"} (see .env.example).'
        )
    return value


_load_dotenv(BASE_DIR / '.env')

# Where the printer/server-side fonts and assets live (downloaded into assets/).
ASSETS_DIR = BASE_DIR / 'assets'
PRINT_FONTS_DIR = ASSETS_DIR / 'fonts'

# Path to the thermal printer device. The TM-T20III shows up as a USB lp device.
PRINTER_DEVICE = '/dev/usb/lp0'

# Password for the hidden /shutdown kiosk command. Checked server-side so it is
# never exposed in the frontend JS.
KIOSK_SHUTDOWN_PASSWORD = _require_env('KIOSK_SHUTDOWN_PASSWORD')

# Password for the hidden /admin kiosk command (wifi config + bash shell).
# Same server-side-only rule applies.
KIOSK_ADMIN_PASSWORD = _require_env('KIOSK_ADMIN_PASSWORD')

# --- LED strip (WS2812B, 15 LEDs on SPI0 MOSI / pin 19) -------------------- #
# Driven by a dedicated daemon (`manage.py leds`), NOT the web workers:
# gunicorn runs 3 processes and SPI is a single hardware resource. Workers fire
# fire-and-forget UDP effect events to the daemon via printer/leds.py.
LED_COUNT = 15
LED_BRIGHTNESS = 0.4          # default/first-run brightness; live value persists below
LED_EVENT_HOST = '127.0.0.1'
LED_EVENT_PORT = 8455

# Sweep speed + brightness are adjusted live (volume keys / `manage.py ledctl`)
# and persisted here so they survive a restart/reboot. divd-owned, writable
# under the service's ProtectSystem=full sandbox; created on first write.
LED_STATE_FILE = '/home/divd/.local/state/divdprint/led-state.json'

# One-shot "boot into a login terminal" flag. When this file exists at boot,
# divd-kiosk.service is skipped (ConditionPathExists=!flag) and getty@tty1
# autologins divd on the main screen instead (ConditionPathExists=flag). divd's
# ~/.profile deletes it on login, so the *next* reboot returns to the kiosk. The
# /admin "login terminal" command writes it then reboots — the in-app
# equivalent of deploy/divd-shell. Must match the path in both unit conditions.
BOOT_TO_SHELL_FLAG = '/home/divd/.boot-to-shell'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _require_env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Reachable from any host (gunicorn binds 0.0.0.0). NOTE: this also exposes
# /submit (prints receipts) and /admin to anyone who can reach the Pi's IP.
ALLOWED_HOSTS = ['*']

# Local kiosk over plain HTTP on loopback; CSRF needs the loopback origins trusted.
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'printer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'divdprint.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'divdprint.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
